export interface Product {
  id: string;
  name: string;
  title: string;
  image: string;
  images: string[]; // Thêm mảng ảnh chi tiết
  currentPrice: number;
  originalPrice: number;
  discount: number;
  rating: number;
  reviews: number;
  tag: "Daily Deals" | "Trending Item" | "Best Choice" | "Best Seller";
  sizes: { value: string; label: string; isBestseller?: boolean }[];
  description: string;
  shippingInfo: string;
  satisfactionGuarantee: string;
  shippingProtection: boolean;
  giftWrapping: boolean;
  material: string; // Added material property
  size: string; // Added size property
}

const tags: (
  | "Daily Deals"
  | "Trending Item"
  | "Best Choice"
  | "Best Seller"
)[] = ["Daily Deals", "Trending Item", "Best Choice", "Best Seller"];

function getRandomTag():
  | "Daily Deals"
  | "Trending Item"
  | "Best Choice"
  | "Best Seller" {
  return tags[Math.floor(Math.random() * tags.length)];
}

function getRandomBoolean(): boolean {
  return Math.random() < 0.5;
}

export const products: Product[] = [
  {
    id: "1",
    name: "y2k-couple-frame",
    title:
      "Y2K Couple Frame Personalized 2-layer Wooden Plaque, Gift for Him, Gift for Her",
    image:
      "https://cdn.shopify.com/s/files/1/0638/0811/0834/files/c4tPqKPs0l__kgkkgfoygq__w1_large.jpg?v=1738661232",
    images: [
      "https://cdn.shopify.com/s/files/1/0638/0811/0834/files/c4tPqKPs0l__kgkkgfoygq__w1_large.jpg?v=1738661232",
      "https://assets.customall.io/3c652c223e657d65757775726a7775687028220a0e140376762318183f2b29213e772c212a29181832227224317f2a7e253618183335247575777573777675747777757372692a3773656b65302e23332f657d6528352e202e29262b656b6532292e33657d65373f656b6530222537657d21262b34226b6533352e2a657d65653a.png",
      "https://example.com/image3.jpg",
    ],
    currentPrice: 27.99,
    originalPrice: 37.99,
    discount: 26,
    rating: 4.8,
    reviews: 886,
    tag: getRandomTag(),
    sizes: [
      { value: "5.5", label: '5.5"' },
      { value: "8", label: '8"', isBestseller: true },
      { value: "10", label: '10"' },
    ],
    description:
      "Khung ảnh đôi Y2K khắc tên theo yêu cầu. Món quà ý nghĩa dành tặng người yêu.",
    shippingInfo: "Giao hàng trong 2-4 ngày",
    satisfactionGuarantee: "Đảm bảo hài lòng 100%",
    shippingProtection: getRandomBoolean(),
    giftWrapping: getRandomBoolean(),
    material: "Wood",
    size: "8 inches",
  },
  {
    id: "2",
    name: "minimalist-wall-art",
    title: "Minimalist Line Art Print, Abstract Wall Decor, Modern Home Art",
    image: "https://example.com/minimalist-art.jpg",
    images: [
      "https://example.com/minimalist-art.jpg",
      "https://example.com/image2.jpg",
    ],
    currentPrice: 19.99,
    originalPrice: 24.99,
    discount: 20,
    rating: 4.6,
    reviews: 520,
    tag: getRandomTag(),
    sizes: [
      { value: "S", label: "Small" },
      { value: "M", label: "Medium", isBestseller: true },
      { value: "L", label: "Large" },
    ],
    description: "Tranh trừu tượng tối giản, phù hợp trang trí mọi không gian.",
    shippingInfo: "Giao hàng trong 3-5 ngày",
    satisfactionGuarantee: "Hoàn tiền nếu không hài lòng",
    shippingProtection: getRandomBoolean(),
    giftWrapping: getRandomBoolean(),
    material: "Paper",
    size: "M",
  },
  {
    id: "3",
    name: "ceramic-coffee-mug",
    title: "Handmade Ceramic Coffee Mug, Unique Glaze, Gift for Coffee Lovers",
    image: "https://example.com/ceramic-mug.jpg",
    images: [
      "https://example.com/ceramic-mug.jpg",
      "https://example.com/image2.jpg",
    ],
    currentPrice: 14.5,
    originalPrice: 18.0,
    discount: 19,
    rating: 4.9,
    reviews: 950,
    tag: getRandomTag(),
    sizes: [
      { value: "12oz", label: "12 oz" },
      { value: "16oz", label: "16 oz" },
    ],
    description:
      "Cốc cà phê gốm thủ công với lớp men độc đáo. Món quà hoàn hảo cho người yêu cà phê.",
    shippingInfo: "Giao hàng trong 1-3 ngày",
    satisfactionGuarantee: "Đổi trả dễ dàng",
    shippingProtection: getRandomBoolean(),
    giftWrapping: getRandomBoolean(),
    material: "Ceramic",
    size: "12oz",
  },
  {
    id: "4",
    name: "leather-wallet-men",
    title: "Genuine Leather Wallet for Men, Slim Design, RFID Blocking",
    image: "https://example.com/leather-wallet.jpg",
    images: [
      "https://example.com/leather-wallet.jpg",
      "https://example.com/image2.jpg",
    ],
    currentPrice: 39.99,
    originalPrice: 49.99,
    discount: 20,
    rating: 4.7,
    reviews: 780,
    tag: getRandomTag(),
    sizes: [{ value: "One Size", label: "One Size" }],
    description: "Ví da thật cho nam, thiết kế mỏng, chống RFID.",
    shippingInfo: "Giao hàng trong 2-4 ngày",
    satisfactionGuarantee: "Bảo hành 1 năm",
    shippingProtection: getRandomBoolean(),
    giftWrapping: getRandomBoolean(),
    material: "Leather",
    size: "One Size",
  },
  {
    id: "5",
    name: "scented-candles-set",
    title: "Scented Candles Gift Set, Natural Soy Wax, Aromatherapy Candles",
    image: "https://example.com/candles-set.jpg",
    images: [
      "https://example.com/candles-set.jpg",
      "https://example.com/image2.jpg",
    ],
    currentPrice: 29.99,
    originalPrice: 35.0,
    discount: 14,
    rating: 4.8,
    reviews: 620,
    tag: getRandomTag(),
    sizes: [
      { value: "Set of 3", label: "Set of 3" },
      { value: "Set of 6", label: "Set of 6" },
    ],
    description:
      "Bộ nến thơm làm từ sáp đậu nành tự nhiên, dùng cho liệu pháp hương thơm.",
    shippingInfo: "Giao hàng trong 3-5 ngày",
    satisfactionGuarantee: "Đảm bảo hương thơm",
    shippingProtection: getRandomBoolean(),
    giftWrapping: getRandomBoolean(),
    material: "Soy Wax",
    size: "Set of 3",
  },
  {
    id: "6",
    name: "boho-throw-blanket",
    title: "Boho Throw Blanket, Soft Knitted Blanket, Decorative Fringe",
    image: "https://example.com/boho-blanket.jpg",
    images: [
      "https://example.com/boho-blanket.jpg",
      "https://example.com/image2.jpg",
    ],
    currentPrice: 45.0,
    originalPrice: 55.0,
    discount: 18,
    rating: 4.7,
    reviews: 480,
    tag: getRandomTag(),
    sizes: [
      { value: "50x60", label: "50x60 inches" },
      { value: "60x80", label: "60x80 inches" },
    ],
    description: "Chăn đắp phong cách boho, mềm mại, có tua rua trang trí.",
    shippingInfo: "Giao hàng trong 4-6 ngày",
    satisfactionGuarantee: "Đảm bảo sự ấm áp",
    shippingProtection: getRandomBoolean(),
    giftWrapping: getRandomBoolean(),
    material: "Cotton",
    size: "50x60 inches",
  },
  {
    id: "7",
    name: "wooden-serving-tray",
    title: "Wooden Serving Tray with Handles, Rustic Farmhouse Style",
    image: "https://example.com/wooden-tray.jpg",
    images: [
      "https://example.com/wooden-tray.jpg",
      "https://example.com/image2.jpg",
    ],
    currentPrice: 32.5,
    originalPrice: 40.0,
    discount: 19,
    rating: 4.6,
    reviews: 350,
    tag: getRandomTag(),
    sizes: [
      { value: "Medium", label: "Medium" },
      { value: "Large", label: "Large" },
    ],
    description: "Khay gỗ phục vụ có tay cầm, phong cách trang trại mộc mạc.",
    shippingInfo: "Giao hàng trong 2-4 ngày",
    satisfactionGuarantee: "Đảm bảo chất lượng gỗ",
    shippingProtection: getRandomBoolean(),
    giftWrapping: getRandomBoolean(),
    material: "Wood",
    size: "Medium",
  },
  {
    id: "8",
    name: "yoga-mat-non-slip",
    title: "Non-Slip Yoga Mat, Eco-Friendly Material, Exercise Mat",
    image: "https://example.com/yoga-mat.jpg",
    images: [
      "https://example.com/yoga-mat.jpg",
      "https://example.com/image2.jpg",
    ],
    currentPrice: 24.0,
    originalPrice: 30.0,
    discount: 20,
    rating: 4.8,
    reviews: 510,
    tag: getRandomTag(),
    sizes: [{ value: "Standard", label: "Standard" }],
    description:
      "Thảm tập yoga chống trượt, chất liệu thân thiện với môi trường.",
    shippingInfo: "Giao hàng trong 1-3 ngày",
    satisfactionGuarantee: "Đảm bảo độ bám dính",
    shippingProtection: getRandomBoolean(),
    giftWrapping: getRandomBoolean(),
    material: "Eco-Friendly Material",
    size: "Standard",
  },
  {
    id: "9",
    name: "bluetooth-speaker-portable",
    title: "Portable Bluetooth Speaker, Waterproof, Loud Sound",
    image: "https://example.com/bluetooth-speaker.jpg",
    images: [
      "https://example.com/bluetooth-speaker.jpg",
      "https://example.com/image2.jpg",
    ],
    currentPrice: 49.99,
    originalPrice: 59.99,
    discount: 17,
    rating: 4.7,
    reviews: 680,
    tag: getRandomTag(),
    sizes: [{ value: "One Size", label: "One Size" }],
    description: "Loa Bluetooth di động, chống nước, âm thanh lớn.",
    shippingInfo: "Giao hàng trong 2-4 ngày",
    satisfactionGuarantee: "Đảm bảo chất lượng âm thanh",
    shippingProtection: getRandomBoolean(),
    giftWrapping: getRandomBoolean(),
    material: "Plastic, Metal",
    size: "One Size",
  },
  {
    id: "10",
    name: "air-purifier-home",
    title: "Air Purifier for Home, HEPA Filter, Removes Allergens",
    image: "https://example.com/air-purifier.jpg",
    images: [
      "https://example.com/air-purifier.jpg",
      "https://example.com/image2.jpg",
    ],
    currentPrice: 79.0,
    originalPrice: 99.0,
    discount: 20,
    rating: 4.6,
    reviews: 420,
    tag: getRandomTag(),
    sizes: [
      { value: "Small Room", label: "Small Room" },
      { value: "Large Room", label: "Large Room" },
    ],
    description:
      "Máy lọc không khí cho gia đình, bộ lọc HEPA, loại bỏ chất gây dị ứng.",
    shippingInfo: "Giao hàng trong 3-5 ngày",
    satisfactionGuarantee: "Đảm bảo chất lượng không khí",
    shippingProtection: getRandomBoolean(),
    giftWrapping: getRandomBoolean(),
    material: "Plastic",
    size: "Small Room",
  },
  {
    id: "11",
    name: "personalized-name-necklace",
    title: "Personalized Name Necklace, Custom Jewelry Gift for Her",
    image: "https://example.com/name-necklace.jpg",
    images: [
      "https://example.com/name-necklace.jpg",
      "https://example.com/image2.jpg",
    ],
    currentPrice: 34.99,
    originalPrice: 45.0,
    discount: 22,
    rating: 4.9,
    reviews: 920,
    tag: getRandomTag(),
    sizes: [
      { value: "16 inches", label: "16 inches" },
      { value: "18 inches", label: "18 inches" },
    ],
    description:
      "Dây chuyền khắc tên theo yêu cầu, món quà trang sức ý nghĩa dành tặng bạn gái.",
    shippingInfo: "Giao hàng trong 5-7 ngày",
    satisfactionGuarantee: "Đảm bảo chất lượng vàng",
    shippingProtection: getRandomBoolean(),
    giftWrapping: getRandomBoolean(),
    material: "Gold",
    size: "16 inches",
  },
  {
    id: "12",
    name: "desk-organizer-accessories",
    title: "Desk Organizer Accessories, Office Supplies Storage",
    image: "https://example.com/desk-organizer.jpg",
    images: [
      "https://example.com/desk-organizer.jpg",
      "https://example.com/image2.jpg",
    ],
    currentPrice: 21.5,
    originalPrice: 26.0,
    discount: 17,
    rating: 4.7,
    reviews: 580,
    tag: getRandomTag(),
    sizes: [{ value: "One Size", label: "One Size" }],
    description: "Bộ phụ kiện sắp xếp bàn làm việc, đựng đồ dùng văn phòng.",
    shippingInfo: "Giao hàng trong 2-4 ngày",
    satisfactionGuarantee: "Đảm bảo không gian gọn gàng",
    shippingProtection: getRandomBoolean(),
    giftWrapping: getRandomBoolean(),
    material: "Plastic",
    size: "One Size",
  },
  {
    id: "13",
    name: "essential-oil-diffuser",
    title:
      "Essential Oil Diffuser, Aromatherapy Diffuser, Ultrasonic Humidifier",
    image: "https://example.com/oil-diffuser.jpg",
    images: [
      "https://example.com/oil-diffuser.jpg",
      "https://example.com/image2.jpg",
    ],
    currentPrice: 38.0,
    originalPrice: 48.0,
    discount: 21,
    rating: 4.8,
    reviews: 710,
    tag: getRandomTag(),
    sizes: [
      { value: "100ml", label: "100ml" },
      { value: "300ml", label: "300ml" },
    ],
    description: "Máy khuếch tán tinh dầu, tạo ẩm không khí bằng sóng siêu âm.",
    shippingInfo: "Giao hàng trong 3-5 ngày",
    satisfactionGuarantee: "Đảm bảo hương thơm",
    shippingProtection: getRandomBoolean(),
    giftWrapping: getRandomBoolean(),
    material: "Plastic, Glass",
    size: "100ml",
  },
  {
    id: "14",
    name: "gardening-tool-set",
    title: "Gardening Tool Set, Heavy Duty Garden Tools, Gardening Gifts",
    image: "https://example.com/garden-tools.jpg",
    images: [
      "https://example.com/garden-tools.jpg",
      "https://example.com/image2.jpg",
    ],
    currentPrice: 42.99,
    originalPrice: 52.0,
    discount: 17,
    rating: 4.6,
    reviews: 490,
    tag: getRandomTag(),
    sizes: [{ value: "Set of 10", label: "Set of 10" }],
    description:
      "Bộ dụng cụ làm vườn chất lượng cao, món quà ý nghĩa cho người yêu cây cảnh.",
    shippingInfo: "Giao hàng trong 4-6 ngày",
    satisfactionGuarantee: "Đảm bảo độ bền",
    shippingProtection: getRandomBoolean(),
    giftWrapping: getRandomBoolean(),
    material: "Metal, Wood",
    size: "Set of 10",
  },
  {
    id: "15",
    name: "kitchen-knife-set",
    title: "Kitchen Knife Set, Stainless Steel Knives, Chef Knife Set",
    image: "https://example.com/kitchen-knives.jpg",
    images: [
      "https://example.com/kitchen-knives.jpg",
      "https://example.com/image2.jpg",
    ],
    currentPrice: 69.0,
    originalPrice: 85.0,
    discount: 19,
    rating: 4.8,
    reviews: 650,
    tag: getRandomTag(),
    sizes: [{ value: "Set of 15", label: "Set of 15" }],
    description: "Bộ dao nhà bếp bằng thép không gỉ, bao gồm dao đầu bếp.",
    shippingInfo: "Giao hàng trong 2-4 ngày",
    satisfactionGuarantee: "Đảm bảo độ sắc bén",
    shippingProtection: getRandomBoolean(),
    giftWrapping: getRandomBoolean(),
    material: "Stainless Steel",
    size: "Set of 15",
  },
  {
    id: "16",
    name: "women's-running-shoes",
    title: "Women's Running Shoes, Lightweight Sneakers, Athletic Shoes",
    image: "https://example.com/running-shoes.jpg",
    images: [
      "https://example.com/running-shoes.jpg",
      "https://example.com/image2.jpg",
    ],
    currentPrice: 55.0,
    originalPrice: 70.0,
    discount: 21,
    rating: 4.7,
    reviews: 720,
    tag: getRandomTag(),
    sizes: [
      { value: "6", label: "6" },
      { value: "7", label: "7" },
      { value: "8", label: "8" },
    ],
    description: "Giày chạy bộ nữ, nhẹ, thích hợp cho các hoạt động thể thao.",
    shippingInfo: "Giao hàng trong 3-5 ngày",
    satisfactionGuarantee: "Đảm bảo sự thoải mái",
    shippingProtection: getRandomBoolean(),
    giftWrapping: getRandomBoolean(),
    material: "Mesh, Rubber",
    size: "6",
  },
  {
    id: "17",
    name: "smartwatch-fitness-tracker",
    title: "Smartwatch Fitness Tracker, Heart Rate Monitor, Sleep Tracking",
    image: "https://example.com/smartwatch.jpg",
    images: [
      "https://example.com/smartwatch.jpg",
      "https://example.com/image2.jpg",
    ],
    currentPrice: 89.99,
    originalPrice: 110.0,
    discount: 18,
    rating: 4.6,
    reviews: 540,
    tag: getRandomTag(),
    sizes: [{ value: "One Size", label: "One Size" }],
    description:
      "Đồng hồ thông minh theo dõi sức khỏe, đo nhịp tim, theo dõi giấc ngủ.",
    shippingInfo: "Giao hàng trong 2-4 ngày",
    satisfactionGuarantee: "Đảm bảo tính năng chính xác",
    shippingProtection: getRandomBoolean(),
    giftWrapping: getRandomBoolean(),
    material: "Metal, Plastic",
    size: "One Size",
  },
  {
    id: "18",
    name: "bluetooth-headphones-noise-cancelling",
    title:
      "Bluetooth Headphones Noise Cancelling, Wireless Over-Ear Headphones",
    image: "https://example.com/headphones.jpg",
    images: [
      "https://example.com/headphones.jpg",
      "https://example.com/image2.jpg",
    ],
    currentPrice: 75.0,
    originalPrice: 92.0,
    discount: 18,
    rating: 4.8,
    reviews: 680,
    tag: getRandomTag(),
    sizes: [{ value: "One Size", label: "One Size" }],
    description: "Tai nghe Bluetooth chống ồn, không dây, trùm đầu.",
    shippingInfo: "Giao hàng trong 3-5 ngày",
    satisfactionGuarantee: "Đảm bảo chất lượng âm thanh",
    shippingProtection: getRandomBoolean(),
    giftWrapping: getRandomBoolean(),
    material: "Plastic, Metal",
    size: "One Size",
  },
  {
    id: "19",
    name: "laptop-backpack-waterproof",
    title: "Laptop Backpack Waterproof, Travel Backpack, Business Backpack",
    image: "https://example.com/laptop-backpack.jpg",
    images: [
      "https://example.com/laptop-backpack.jpg",
      "https://example.com/image2.jpg",
    ],
    currentPrice: 48.5,
    originalPrice: 60.0,
    discount: 19,
    rating: 4.7,
    reviews: 490,
    tag: getRandomTag(),
    sizes: [
      { value: "Medium", label: "Medium" },
      { value: "Large", label: "Large" },
    ],
    description: "Ba lô đựng laptop chống nước, thích hợp du lịch và công tác.",
    shippingInfo: "Giao hàng trong 2-4 ngày",
    satisfactionGuarantee: "Đảm bảo độ bền",
    shippingProtection: getRandomBoolean(),
    giftWrapping: getRandomBoolean(),
    material: "Nylon",
    size: "Medium",
  },
  {
    id: "20",
    name: "digital-camera-4k",
    title: "Digital Camera 4K, Vlog Camera, Camera for Photography",
    image: "https://example.com/digital-camera.jpg",
    images: [
      "https://example.com/digital-camera.jpg",
      "https://example.com/image2.jpg",
    ],
    currentPrice: 399.0,
    originalPrice: 450.0,
    discount: 11,
    rating: 4.5,
    reviews: 380,
    tag: getRandomTag(),
    sizes: [{ value: "One Size", label: "One Size" }],
    description: "Máy ảnh kỹ thuật số 4K, thích hợp quay vlog và chụp ảnh.",
    shippingInfo: "Giao hàng trong 3-5 ngày",
    satisfactionGuarantee: "Đảm bảo chất lượng hình ảnh",
    shippingProtection: getRandomBoolean(),
    giftWrapping: getRandomBoolean(),
    material: "Plastic, Metal",
    size: "One Size",
  },
  {
    id: "21",
    name: "men's-casual-shirt",
    title: "Men's Casual Shirt, Slim Fit, Long Sleeve Button-Down Shirt",
    image: "https://example.com/mens-shirt.jpg",
    images: [
      "https://example.com/mens-shirt.jpg",
      "https://example.com/image2.jpg",
    ],
    currentPrice: 28.0,
    originalPrice: 35.0,
    discount: 20,
    rating: 4.6,
    reviews: 510,
    tag: getRandomTag(),
    sizes: [
      { value: "S", label: "S" },
      { value: "M", label: "M" },
      { value: "L", label: "L" },
    ],
    description: "Áo sơ mi nam, dáng ôm, tay dài, cài nút.",
    shippingInfo: "Giao hàng trong 2-4 ngày",
    satisfactionGuarantee: "Đảm bảo chất liệu vải",
    shippingProtection: getRandomBoolean(),
    giftWrapping: getRandomBoolean(),
    material: "Cotton",
    size: "S",
  },
  {
    id: "22",
    name: "women's-dress-floral",
    title: "Women's Dress Floral, Summer Dress, Midi Dress",
    image: "https://example.com/womens-dress.jpg",
    images: [
      "https://example.com/womens-dress.jpg",
      "https://example.com/image2.jpg",
    ],
    currentPrice: 32.5,
    originalPrice: 40.0,
    discount: 19,
    rating: 4.7,
    reviews: 630,
    tag: getRandomTag(),
    sizes: [
      { value: "XS", label: "XS" },
      { value: "S", label: "S" },
      { value: "M", label: "M" },
    ],
    description: "Váy hoa nữ, váy mùa hè, dáng midi.",
    shippingInfo: "Giao hàng trong 3-5 ngày",
    satisfactionGuarantee: "Đảm bảo kiểu dáng",
    shippingProtection: getRandomBoolean(),
    giftWrapping: getRandomBoolean(),
    material: "Cotton",
    size: "XS",
  },
  {
    id: "23",
    name: "baby-toys-educational",
    title: "Baby Toys Educational, Wooden Toys, Learning Toys for Toddlers",
    image: "https://example.com/baby-toys.jpg",
    images: [
      "https://example.com/baby-toys.jpg",
      "https://example.com/image2.jpg",
    ],
    currentPrice: 25.0,
    originalPrice: 30.0,
    discount: 17,
    rating: 4.8,
    reviews: 480,
    tag: getRandomTag(),
    sizes: [{ value: "One Size", label: "One Size" }],
    description:
      "Đồ chơi cho bé, đồ chơi gỗ, đồ chơi giáo dục cho trẻ mới biết đi.",
    shippingInfo: "Giao hàng trong 2-4 ngày",
    satisfactionGuarantee: "Đảm bảo an toàn cho bé",
    shippingProtection: getRandomBoolean(),
    giftWrapping: getRandomBoolean(),
    material: "Wood",
    size: "One Size",
  },
  {
    id: "24",
    name: "pet-bed-dog-cat",
    title: "Pet Bed Dog Cat, Soft Plush Bed, Washable Pet Bed",
    image: "https://example.com/pet-bed.jpg",
    images: [
      "https://example.com/pet-bed.jpg",
      "https://example.com/image2.jpg",
    ],
    currentPrice: 36.0,
    originalPrice: 45.0,
    discount: 20,
    rating: 4.6,
    reviews: 520,
    tag: getRandomTag(),
    sizes: [
      { value: "Small", label: "Small" },
      { value: "Medium", label: "Medium" },
      { value: "Large", label: "Large" },
    ],
    description: "Giường cho chó mèo, mềm mại, có thể giặt được.",
    shippingInfo: "Giao hàng trong 3-5 ngày",
    satisfactionGuarantee: "Đảm bảo sự thoải mái cho thú cưng",
    shippingProtection: getRandomBoolean(),
    giftWrapping: getRandomBoolean(),
    material: "Plush",
    size: "Small",
  },
  {
    id: "25",
    name: "book-self-help",
    title: "Book Self Help, Personal Development Book, Motivational Book",
    image: "https://example.com/self-help-book.jpg",
    images: [
      "https://example.com/self-help-book.jpg",
      "https://example.com/image2.jpg",
    ],
    currentPrice: 15.0,
    originalPrice: 18.0,
    discount: 17,
    rating: 4.7,
    reviews: 650,
    tag: getRandomTag(),
    sizes: [
      { value: "Paperback", label: "Paperback" },
      { value: "Hardcover", label: "Hardcover" },
    ],
    description:
      "Sách self-help, sách phát triển bản thân, sách truyền động lực.",
    shippingInfo: "Giao hàng trong 2-4 ngày",
    satisfactionGuarantee: "Đảm bảo nội dung hữu ích",
    shippingProtection: getRandomBoolean(),
    giftWrapping: getRandomBoolean(),
    material: "Paper",
    size: "Paperback",
  },
  {
    id: "26",
    name: "wall-clock-modern",
    title: "Wall Clock Modern, Silent Non-Ticking, Decorative Wall Clock",
    image: "https://example.com/wall-clock.jpg",
    images: [
      "https://example.com/wall-clock.jpg",
      "https://example.com/image2.jpg",
    ],
    currentPrice: 22.0,
    originalPrice: 27.0,
    discount: 19,
    rating: 4.5,
    reviews: 390,
    tag: getRandomTag(),
    sizes: [{ value: "12 inches", label: "12 inches" }],
    description: "Đồng hồ treo tường hiện đại, không gây tiếng ồn, trang trí.",
    shippingInfo: "Giao hàng trong 3-5 ngày",
    satisfactionGuarantee: "Đảm bảo hoạt động chính xác",
    shippingProtection: getRandomBoolean(),
    giftWrapping: getRandomBoolean(),
    material: "Plastic, Glass",
    size: "12 inches",
  },
  {
    id: "27",
    name: "table-lamp-led",
    title: "Table Lamp LED, Desk Lamp, Adjustable Brightness",
    image: "https://example.com/table-lamp.jpg",
    images: [
      "https://example.com/table-lamp.jpg",
      "https://example.com/image2.jpg",
    ],
    currentPrice: 29.99,
    originalPrice: 35.0,
    discount: 14,
    rating: 4.7,
    reviews: 540,
    tag: getRandomTag(),
    sizes: [{ value: "One Size", label: "One Size" }],
    description: "Đèn bàn LED, điều chỉnh độ sáng.",
    shippingInfo: "Giao hàng trong 2-4 ngày",
    satisfactionGuarantee: "Đảm bảo ánh sáng tốt",
    shippingProtection: getRandomBoolean(),
    giftWrapping: getRandomBoolean(),
    material: "Metal, Plastic",
    size: "One Size",
  },
  {
    id: "28",
    name: "picture-frames-set",
    title: "Picture Frames Set, Photo Frames, Wall Decor Frames",
    image: "https://example.com/picture-frames.jpg",
    images: [
      "https://example.com/picture-frames.jpg",
      "https://example.com/image2.jpg",
    ],
    currentPrice: 38.5,
    originalPrice: 45.0,
    discount: 14,
    rating: 4.6,
    reviews: 420,
    tag: getRandomTag(),
    sizes: [
      { value: "Set of 5", label: "Set of 5" },
      { value: "Set of 10", label: "Set of 10" },
    ],
    description: "Bộ khung ảnh, khung ảnh treo tường.",
    shippingInfo: "Giao hàng trong 3-5 ngày",
    satisfactionGuarantee: "Đảm bảo chất liệu khung",
    shippingProtection: getRandomBoolean(),
    giftWrapping: getRandomBoolean(),
    material: "Wood, Glass",
    size: "Set of 5",
  },
  {
    id: "29",
    name: "shower-curtain-waterproof",
    title: "Shower Curtain Waterproof, Fabric Shower Curtain, Bathroom Decor",
    image: "https://example.com/shower-curtain.jpg",
    images: [
      "https://example.com/shower-curtain.jpg",
      "https://example.com/image2.jpg",
    ],
    currentPrice: 21.0,
    originalPrice: 25.0,
    discount: 16,
    rating: 4.8,
    reviews: 590,
    tag: getRandomTag(),
    sizes: [{ value: "Standard", label: "Standard" }],
    description: "Rèm phòng tắm chống thấm nước.",
    shippingInfo: "Giao hàng trong 2-4 ngày",
    satisfactionGuarantee: "Đảm bảo khả năng chống thấm nước",
    shippingProtection: getRandomBoolean(),
    giftWrapping: getRandomBoolean(),
    material: "Polyester",
    size: "Standard",
  },
  {
    id: "30",
    name: "rug-area-carpet",
    title: "Rug Area Carpet, Soft Fluffy Rug, Living Room Rug",
    image: "https://example.com/rug.jpg",
    images: ["https://example.com/rug.jpg", "https://example.com/image2.jpg"],
    currentPrice: 55.0,
    originalPrice: 65.0,
    discount: 15,
    rating: 4.7,
    reviews: 470,
    tag: getRandomTag(),
    sizes: [
      { value: "4x6", label: "4x6 feet" },
      { value: "5x8", label: "5x8 feet" },
    ],
    description: "Thảm trải sàn, mềm mại.",
    shippingInfo: "Giao hàng trong 3-5 ngày",
    satisfactionGuarantee: "Đảm bảo chất liệu thảm",
    shippingProtection: getRandomBoolean(),
    giftWrapping: getRandomBoolean(),
    material: "Polyester",
    size: "4x6 feet",
  },
  {
    id: "31",
    name: "coffee-maker-drip",
    title: "Coffee Maker Drip, Programmable Coffee Maker, Coffee Machine",
    image: "https://example.com/coffee-maker.jpg",
    images: [
      "https://example.com/coffee-maker.jpg",
      "https://example.com/image2.jpg",
    ],
    currentPrice: 44.0,
    originalPrice: 52.0,
    discount: 15,
    rating: 4.6,
    reviews: 410,
    tag: getRandomTag(),
    sizes: [{ value: "12-Cup", label: "12-Cup" }],
    description: "Máy pha cà phê.",
    shippingInfo: "Giao hàng trong 2-4 ngày",
    satisfactionGuarantee: "Đảm bảo chất lượng cà phê",
    shippingProtection: getRandomBoolean(),
    giftWrapping: getRandomBoolean(),
    material: "Plastic, Glass",
    size: "12-Cup",
  },
  {
    id: "32",
    name: "blender-smoothie-maker",
    title: "Blender Smoothie Maker, Professional Blender, Kitchen Blender",
    image: "https://example.com/blender.jpg",
    images: [
      "https://example.com/blender.jpg",
      "https://example.com/image2.jpg",
    ],
    currentPrice: 62.0,
    originalPrice: 75.0,
    discount: 17,
    rating: 4.7,
    reviews: 560,
    tag: getRandomTag(),
    sizes: [{ value: "One Size", label: "One Size" }],
    description: "Máy xay sinh tố.",
    shippingInfo: "Giao hàng trong 3-5 ngày",
    satisfactionGuarantee: "Đảm bảo độ bền",
    shippingProtection: getRandomBoolean(),
    giftWrapping: getRandomBoolean(),
    material: "Plastic, Stainless Steel",
    size: "One Size",
  },
  {
    id: "33",
    name: "toaster-2-slice",
    title: "Toaster 2 Slice, Stainless Steel Toaster, Bread Toaster",
    image: "https://example.com/toaster.jpg",
    images: [
      "https://example.com/toaster.jpg",
      "https://example.com/image2.jpg",
    ],
    currentPrice: 26.0,
    originalPrice: 30.0,
    discount: 13,
    rating: 4.5,
    reviews: 380,
    tag: getRandomTag(),
    sizes: [{ value: "2-Slice", label: "2-Slice" }],
    description: "Máy nướng bánh mỳ.",
    shippingInfo: "Giao hàng trong 2-4 ngày",
    satisfactionGuarantee: "Đảm bảo chất lượng nướng",
    shippingProtection: getRandomBoolean(),
    giftWrapping: getRandomBoolean(),
    material: "Stainless Steel",
    size: "2-Slice",
  },
  {
    id: "35",
    name: "hand-mixer-electric",
    title: "Hand Mixer Electric, Kitchen Mixer, Baking Mixer",
    image: "https://example.com/hand-mixer.jpg",
    images: [
      "https://example.com/hand-mixer.jpg",
      "https://example.com/image2.jpg",
    ],
    currentPrice: 32.0,
    originalPrice: 38.0,
    discount: 16,
    rating: 4.6,
    reviews: 420,
    tag: getRandomTag(),
    sizes: [{ value: "One Size", label: "One Size" }],
    description: "Máy trộn cầm tay.",
    shippingInfo: "Giao hàng trong 2-4 ngày",
    satisfactionGuarantee: "Đảm bảo trộn đều",
    shippingProtection: getRandomBoolean(),
    giftWrapping: getRandomBoolean(),
    material: "Plastic, Metal",
    size: "One Size",
  },
  {
    id: "36",
    name: "baby-carrier-ergonomic",
    title: "Baby Carrier Ergonomic, Front and Back Carrier, Newborn Carrier",
    image: "https://example.com/baby-carrier.jpg",
    images: [
      "https://example.com/baby-carrier.jpg",
      "https://example.com/image2.jpg",
    ],
    currentPrice: 48.0,
    originalPrice: 55.0,
    discount: 13,
    rating: 4.8,
    reviews: 580,
    tag: getRandomTag(),
    sizes: [{ value: "One Size", label: "One Size" }],
    description: "Địu em bé.",
    shippingInfo: "Giao hàng trong 3-5 ngày",
    satisfactionGuarantee: "Đảm bảo an toàn cho bé",
    shippingProtection: getRandomBoolean(),
    giftWrapping: getRandomBoolean(),
    material: "Cotton, Polyester",
    size: "One Size",
  },
  {
    id: "37",
    name: "baby-monitor-video",
    title: "Baby Monitor Video, Night Vision, Two-Way Audio",
    image: "https://example.com/baby-monitor.jpg",
    images: [
      "https://example.com/baby-monitor.jpg",
      "https://example.com/image2.jpg",
    ],
    currentPrice: 65.0,
    originalPrice: 75.0,
    discount: 13,
    rating: 4.7,
    reviews: 450,
    tag: getRandomTag(),
    sizes: [{ value: "One Size", label: "One Size" }],
    description: "Máy báo khóc.",
    shippingInfo: "Giao hàng trong 2-4 ngày",
    satisfactionGuarantee: "Đảm bảo hình ảnh rõ nét",
    shippingProtection: getRandomBoolean(),
    giftWrapping: getRandomBoolean(),
    material: "Plastic",
    size: "One Size",
  },
  {
    id: "38",
    name: "diaper-bag-backpack",
    title: "Diaper Bag Backpack, Large Capacity, Insulated Pockets",
    image: "https://example.com/diaper-bag.jpg",
    images: [
      "https://example.com/diaper-bag.jpg",
      "https://example.com/image2.jpg",
    ],
    currentPrice: 42.0,
    originalPrice: 49.0,
    discount: 14,
    rating: 4.6,
    reviews: 520,
    tag: getRandomTag(),
    sizes: [{ value: "One Size", label: "One Size" }],
    description: "Balo đựng tã.",
    shippingInfo: "Giao hàng trong 3-5 ngày",
    satisfactionGuarantee: "Đảm bảo sức chứa lớn",
    shippingProtection: getRandomBoolean(),
    giftWrapping: getRandomBoolean(),
    material: "Polyester",
    size: "One Size",
  },
  {
    id: "39",
    name: "car-seat-infant",
    title: "Car Seat Infant, Convertible Car Seat, Safety Car Seat",
    image: "https://example.com/car-seat.jpg",
    images: [
      "https://example.com/car-seat.jpg",
      "https://example.com/image2.jpg",
    ],
    currentPrice: 95.0,
    originalPrice: 110.0,
    discount: 14,
    rating: 4.8,
    reviews: 610,
    tag: getRandomTag(),
    sizes: [{ value: "One Size", label: "One Size" }],
    description: "Ghế ô tô cho trẻ sơ sinh.",
    shippingInfo: "Giao hàng trong 2-4 ngày",
    satisfactionGuarantee: "Đảm bảo an toàn",
    shippingProtection: getRandomBoolean(),
    giftWrapping: getRandomBoolean(),
    material: "Plastic, Fabric",
    size: "One Size",
  },
  {
    id: "40",
    name: "stroller-travel-system",
    title: "Stroller Travel System, Lightweight Stroller, Baby Stroller",
    image: "https://example.com/stroller.jpg",
    images: [
      "https://example.com/stroller.jpg",
      "https://example.com/image2.jpg",
    ],
    currentPrice: 120.0,
    originalPrice: 140.0,
    discount: 14,
    rating: 4.7,
    reviews: 550,
    tag: getRandomTag(),
    sizes: [{ value: "One Size", label: "One Size" }],
    description: "Xe đẩy em bé.",
    shippingInfo: "Giao hàng trong 3-5 ngày",
    satisfactionGuarantee: "Đảm bảo trọng lượng nhẹ",
    shippingProtection: getRandomBoolean(),
    giftWrapping: getRandomBoolean(),
    material: "Metal, Fabric, Plastic",
    size: "One Size",
  },
];
